<div class="container">
    <div class="row">        
            <div class="listNews">
                <?php
                if (empty($news)) {
                    echo '<div class="alert alert-info">Нет результатов</div>';
                } else {
                    
                    foreach ($news as $newsResult) {
                        $commentCount = array();
                        foreach ($comments as $commentsResult){
                            if($newsResult->getId() == $commentsResult->getNews()->getId()){
                                $commentCount[] = $commentsResult->getComments()->getId(); 
                            }
                        }
                            
                            echo '<div id="newsBlock" class="col-md-4">';
                            echo '<a href="/news/' .$newsResult->getTime()->format('Y').'/' .$newsResult->getTime()->format('m'). '/'.$newsResult->getTime()->format('d').'/'. $newsResult->getId() . '">';
                            echo '<div class="thumbnail">';
                            echo '<img style="width: 300px; height: 200px;" data-src="' . $newsResult->getImg() . '">';
                            echo '<h3>' .$newsResult->getName() . '</h3>';
                            echo '<div class="caption">' . $newsResult->getShortText() . '</div>';
                            
                            echo '</a>';
                            
                            echo '<span class="badge">'.count($commentCount).'</span> Комментариев ';
                            echo '</div>';
                            echo '</div>';
                            echo '</div>';
                            
                        
                    }
                };
                ?>
            
        </div>
    </div>
</div>
