
<div class="row">        
    <div class="col-md-4"> 
        <a href="/news/<?php $date = new \DateTime; echo $date->format('Y') . '/' . $date->format('m') . '/' . $date->format('d');   ?>"><button class="btn btn-default">Новости за сегодня</button></a>
    </div>
</div>
<div class="row">  
    <div class="listNews">

        <?php if (empty($news)) : ?>
            <div class="alert alert-info">Нет результатов</div>
        <?php else : ?>

            <?php foreach ($news as $newsResult) : ?>
                <div id="newsBlock" class="col-md-12">
                    <a href="/news/<?= $newsResult->getTime()->format('Y') ?>/<?= $newsResult->getTime()->format('m') ?>/<?= $newsResult->getTime()->format('d') ?>/<?= $newsResult->getId() ?>">
                        <div class="thumbnail">
                            <div class="row">
                                <div class="col-md-5">
                                    <img style="width: 300px; height: 200px;" data-src="<?= $newsResult->getImg() ?>"/>
                                </div> 
                                <div class="col-md-7">
                            <h3><?= $newsResult->getName() ?></h3>
                            <div class="caption"><?= $newsResult->getShortText() ?></div>
                            </div>
                                </div>
                    </a>
                    <span class="badge"><?= $newsResult->getComments() ?></span> Обсуждение 
                </div>
            </div>
        <?php endforeach; ?>            
    <?php endif; ?>
</div>

</div>

