
    <div class="row">        
        <div class="listNews">
            <?php
            if (empty($news)) :?>
                <div class="alert alert-info">Нет результатов</div>
            <?php else :?>

               <?php foreach ($news as $newsResult) :?>
                    <?php $commentCount = array();
                    foreach ($comments as $commentsResult) {
                         if ($newsResult->getId() == $commentsResult->getNews()->getId()) {
                            $commentCount[] = $commentsResult->getComments()->getId();
                        }
                    }
                    ?>
                    
<a href="/news/<?= $newsResult->getTime()->format('Y') ?>/<?= $newsResult->getTime()->format('m') ?>/<?= $newsResult->getTime()->format('d') ?>/<?= $newsResult->getId() ?>">
                        <div class="thumbnail">
                            <div class="row">
                                <div class="col-md-5">
                                    <img style="width: 300px; height: 200px;" data-src="<?= $newsResult->getImg() ?>"/>
                                </div> 
                                <div class="col-md-7">
                            <h3><?= $newsResult->getName() ?></h3>
                            <div class="caption"><?= $newsResult->getShortText() ?></div>
                            </div>
                                </div>
                    </a>
                    <span class="badge"><?= count($commentCount) ?></span> Комментариев 
                    </div>
                    
                <?php endforeach;?>            
            <?php endif;?>
        </div>
    
    </div>

