
    <div class="row">
        <div class="col-md-3">
            <form id="addNews" action="#" method="POST">
                <input type="text" name="newsName" placeholder="Заголовок"/>
                <textarea name="newsShortText" rows="10" cols="50" placeholder="Вступительный текст"></textarea>
                <input type="file" name="newsImage"/>
                <textarea name="newsFullText" rows="10" cols="90" placeholder="Текст для детальной страницы"></textarea>
                
                <input type="submit" class="btn btn-success" value="Добавить"/>
            </form>    
        </div>
    </div>


