<script type="text/javascript">
    $(function() {
        $('.like').click(function() {
            id = $(this).attr("data-id");
            like = $(this).attr("data-like");
            likeDislike(id, like);
        });
    });
    function likeDislike(id, like) {
        var data = 'id=' + id + '&like=' + like;
        $.ajax({
            type: 'POST',
            url: '#',            
            data: data,
            success: function(res){
                $('body').html(res);
                    }
            
        });
    }
    
    $(function(){
        $('#addComment').click(function(e){
            e.preventDefault();
            
            
        });
        
    });
   

</script>
<div class="container">
    <div class="row">
        <div id="newsBlock" class="col-md-12">        
            <?php if (empty($news)): ?>
                <div class="alert alert-info">Такой новости не существует</div>
            <?php else : ?>
                <?php
                function comToCom($arrayCommentsToComments, $valuePrimary) {
                    foreach ($arrayCommentsToComments as $value) {
                          if ($value->getParent()->getId() == $valuePrimary->getChild()->getId()) : ?>                            
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <div class="row">
                                        <div class="col-md-3">   
                                            <?= $value->getChild()->getTime()->format('Y-m-d H:m') ?>
                                        </div>
                                        <div class="col-md-7"></div>
                                        <div class="col-md-2">   
                                    <span class="likeCount"><?= $value->getChild()->getLike() ?></span>
                                    <button data-id="<?= $value->getChild()->getId() ?>" data-like="1" class="like btn btn-xs btn-success">+</button>
                                    <button data-id="<?= $value->getChild()->getId() ?>" data-like="-1" class="like btn btn-xs btn-danger">-</button>
                                    <span class="dislikeCount"> <?= $value->getChild()->getDisLike() ?></span>
                                    </div>
                                        </div>
                                </div>
                                <div class="panel-body">
                            <?= $value->getChild()->getText() ?>
                            <?= comToCom($arrayCommentsToComments, $value) ?>
                                </div>
                            </div>                          
                <?php endif;}}?>                     
                    

                  <?php foreach ($news as $newsResult) : ?>
                    <div class="blog-post">
                        <h3 class="blog-post-title"><?= $newsResult->getName() ?></h3>
                        <div class="caption"><?= $newsResult->getFullText() ?></div>
                    </div>
                  <?php endforeach; ?>

                <div id="commentsList" >
                            <div class="well-lg">
                                <form name="newComment" method="POST" action="#" >
                                    <input type="text" class="form-control" name="email" placeholder="Author id"/>                                      
                                    <textarea class="form-control" rows="3" placeholder="Ведите текст" name="textNewComment"></textarea>
                                    <input id="addComment" type="submit" class="btn btn-success"/> 
                                </form>
                                </div>   
                  <?php foreach ($commentsToNews as $commentsToNewsResult) : ?>
                        <div id="parent" class="panel panel-default">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-md-3">
                                        <?= $commentsToNewsResult->getComments()->getTime()->format('Y-m-d H-m') ?>
                                    </div>
                                    <div class="col-md-7"></div>
                                    <div class="col-md-2">
                                        <span class="likeCount"><?= $commentsToNewsResult->getComments()->getLike() ?></span>
                                        <button data-like="1" data-id="<?= $commentsToNewsResult->getComments()->getId() ?>" class="like btn btn-xs btn-success">+</button>
                                        <button data-id="<?= $commentsToNewsResult->getComments()->getId() ?>" data-like="-1" class="like btn btn-xs btn-danger">-</button>
                                        <span class="dislikeCount"> <?= $commentsToNewsResult->getComments()->getDisLike() ?></span>
                                    </div>
                                </div>
                            </div>
                            <div class="panel-body">
                                <?= $commentsToNewsResult->getComments()->getText() ?>                                
                                        <?php foreach ($commentsToComments as $value) : ?>
                                         <?php if ($value->getParent()->getId() === $commentsToNewsResult->getComments()->getId()) : ?>                                        
                                        <div id="child" class="panel panel-default">
                                            <div class="panel-heading">
                                             <div class="row">
                                              <div class="col-md-3">
                                               <?= $value->getChild()->getTime()->format('Y-m-d H-m') ?>
                                                  </div>
                                                 <div class="col-md-7"></div>
                                    <div class="col-md-2">
                                                <span class="likeCount"><?= $value->getChild()->getLike() ?> </span>
                                                <button data-id="<?= $value->getChild()->getId() ?>" data-like="1" class="like btn btn-xs btn-success">+</button>
                                                <button data-id="<?= $value->getChild()->getId() ?>" data-like="-1" class="like btn btn-xs btn-danger">-</button>
                                                <span class="dislikeCount"><?= $value->getChild()->getDisLike() ?></span>                                            
                                                    </div>
                                                </div>
                                                </div>
                                            <div class="panel-body">
                                                <?= $value->getChild()->getText() ?>
                                        <?= comToCom($commentsToComments, $value) ?>
                                            </div>
                                        </div>
                            <?php endif; ?>
                    <?php endforeach; ?>
                            </div>
                        </div>
                <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>


