
    <div class="row">
        <div id="newsBlock" class="col-md-12">        
            <?php if (empty($news)): ?>
                <div class="alert alert-info">Такой новости не существует</div>
            <?php else : ?>
                

                  <?php foreach ($news as $newsResult) : ?>
                    <div class="blog-post">
                        <h3 class="blog-post-title"><?= $newsResult->getName() ?></h3>
                        <div class="caption"><?= $newsResult->getFullText() ?></div>
                    </div>
                 Обсуждение <span class="badge"><?= $newsResult->getComments() ?></span>
                  <?php endforeach; ?>                
                <?php echo $this->comments;?>
            <?php endif; ?>
        </div>
    </div>



