
    <div class="row">

        <form id="filter" action="/salary/search" class="navbar-form" method="get">

            <div class="form-group">
                <select name="technology" select class="form-control">
                    <option value="0">Выберите технологию:</option>
                    <?php foreach ($technology as $value): ?>
                        <option value="<?= $value->getId() ?>"><?= $value->getName() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group">
                <select name="position" select class="form-control">
                    <option value="0">Выберите должность:</option>
                    <?php foreach ($position as $value): ?>
                        <option value="<?= $value->getId() ?>"><?= $value->getName() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group">
                <select name="city" select class="form-control">
                    <option value="0">Выберите город:</option>
                    <?php foreach ($city as $value): ?>
                        <option value="<?= $value->getId() ?>"><?= $value->getName() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group">
                <input type="text" class="form-control" name="experience" size="8" maxlength="2" value="" placeholder="Стаж, лет"  />
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="price" size="6" maxlength="4" placeholder="Сумма, $" value="" />
            </div>


            <input type="reset" class="btn btn-danger" value="Clear Form" />
            <input type="submit" class="btn btn-success" id="LogIn" value="GO!"> 

        </form>

    </div>


    <div class="row">
        <div class="col-md-9">

            <?php

            class Graphical {

                public $price = array();
                public $january = '2014-01';
                public $february = '2014-02';
                public $march = '2014-03';
                public $april = '2014-04';
                public $result;

                public function graphPrice($array, $month) {
                    if ($array['date_create']->format('Y-m') == $month) {
                        $this->price[] = $array['price'];
                    }
                    return $this->price;
                }

                public function meanPrice($price_array) {
                    $this->result = array_sum($price_array) / count($price_array);
                    return $this->result;
                }

            }

            $january = new Graphical();
            $february = new Graphical();
            $march = new Graphical();
            $april = new Graphical();

            foreach ($date as $value) {
                $january->graphPrice($value, $january->january);
                $february->graphPrice($value, $february->february);
                $march->graphPrice($value, $march->march);
                $april->graphPrice($value, $april->april);
            }
            ?>  
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>$</th>
                        <th>Январь</th>
                        <th>Февраль</th>
                        <th>Март</th>
                        <th>Апрель</th>
                    </tr>  
                </thead>
                <tbody>
                    <tr>
                        <td>
                            10000
                        </td>
                    </tr>
                    <tr>
                        <td>
                            5000
                        </td>
                    </tr>
                    <tr>
                        <td>
                            3000
                        </td>
                        <td>                        
                        </td>
                        <td>                        
                        </td>
                        <td>                        
                        </td>
                        <td>
                            <?php
                            if (empty($april->price)) {
                                
                            } else {
                                $april->meanPrice($april->price);
                                echo $april->result;
                            }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            1000
                        </td>

                        <td>
                            <?php
                            if (empty($january->price)) {
                                
                            } else {
                                $january->meanPrice($january->price);
                                echo $january->result;
                            }
                            ?>
                        </td>
                        <td>
                            <?php
                            if (empty($february->price)) {
                                
                            } else {
                                $february->meanPrice($february->price);
                                echo $february->result;
                            }
                            ?>
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>
                            0
                        </td>
                        <td>

                        </td>
                        <td>

                        </td>

                        <td>
                            <?php
                            if (empty($march->price)) {
                                echo '0';
                            } else {
                                $march->meanPrice($march->price);
                                echo $march->result;
                            }
                            ?>
                        </td>
                    </tr>
                    <tr>

                    </tr>
                </tbody>
            </table>
        </div>

    </div>
    <div class="row">
        <div class="col-md-9">
            <div class="listVacancy">
                <?php
                if (empty($vacancy)) {
                    echo '<div class="alert alert-info">Нет результатов</div>';
                } else {
                    $today = new \DateTime('now');
                    foreach ($vacancy as $vacancyResult) {
                        if ($vacancyResult->getDateEnd()->format('Y-m-d H:i:s') >= $today->format('Y-m-d H:i:s')) {
                            echo '<div class="panel panel-default">';
                            echo '<div class="panel-heading">                           
                        <h3 class="panel-title"><a href="vacancy/detail/' . $vacancyResult->getId() . '">' . $vacancyResult->getName() . '</a></h3>
                        </div>';
                            echo '<div class="panel-body">' . substr($vacancyResult->getDescription(),0,500) . '</div>';
                            echo '<div class="panel-footer">';
                            echo '<div class="row">';
                            echo '<div class="price col-md-2">' . $vacancyResult->getPrice() . ' $</div>';
                            echo '<div class="company col-md-8">';
                            foreach ($companyVacancy as $companyResult) {
                                switch ($vacancyResult->getId()) {
                                    case $companyResult->getVacancy()->getId():
                                        echo '<a   href="/company/' . $companyResult->getCompany()->getId() . '">' . $companyResult->getCompany()->getName() . '</a>';
                                }
                            }
                            echo '</div>';
                            echo '<div class="linkDetail col-md-2"><a href="/vacancy/detail/' . $vacancyResult->getId() . '"><button type="button" class="btn btn-info">Подробнее</button></a></div>';
                            echo '</div>';
                            echo '</div>';
                            echo '</div>';
                        }
                    }
                };
                ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-primary">
                <div class="panel panel-heading">Свежедобавленные вакансии</div>
                <div class="panel-body">
                    <ul class="list-group">
                        <?php
                        $id = array();
                        foreach ($vacancy as $value) {
                           $id[] = $value->getId();
                            
                        }
                            $maxId = max($id);
                            $countVacancy = 4;
                            $minId = $maxId - $countVacancy;
                        foreach ($vacancy as $value) {
                            if ($value->getId() == $maxId || $value->getId() >= $minId) {
                                echo '<a href="vacancy/detail/' . $value->getId() . '">';
                                echo '<li class="list-group-item">';
                                echo '<span class="badge">' . $value->getPrice() . '$ </span>';
                                echo $value->getName();
                                echo '</li>';
                                echo '</a>';
                            }
                        }
                        ?>


                    </ul>
                </div>
            </div>
        </div>

        <a href="/vacancy/add"><button class="btn btn-success">Добавить вакансию</button></a>

    </div>


