<div class="container">
    <div class="row">

        <form id="filter" action="salary/search" class="navbar-form" method="get">

            <div class="col-md-2">
                <select name="technology" select class="form-control">
                    <option value="0">Выберите технологию:</option>
                    <?php foreach ($technology as $value): ?>
                        <option value="<?php echo $value->getId() ?>"><?php echo $value->getName() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="col-md-3">
                <select name="position" select class="form-control">
                    <option value="0">Выберите должность:</option>
                    <?php foreach ($position as $value): ?>
                        <option value="<?php echo $value->getId() ?>"><?php echo $value->getName() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="col-md-2">
                <select name="city" select class="form-control">
                    <option value="0">Выберите город:</option>
                    <?php foreach ($city as $value): ?>
                        <option value="<?php echo $value->getId() ?>"><?php echo $value->getName() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="col-md-1">
                <input type="text" class="form-control" name="experience" size="6" maxlength="2" placeholder="Стаж, лет" />
            </div>
            <div class="col-md-1">
                <input type="text" class="form-control" name="price" size="6" maxlength="4" placeholder="Сумма, $" />
            </div>


            <input type="reset" class="btn btn-danger" value="Clear Form" />
            <input type="submit" class="btn btn-success" id="LogIn" value="GO!"> 

        </form>

    </div>
</div>
<div class="container">
    <div class="row">
        <?php
        class Graphical {
            public $price = array();
            public $january = '2014-01';
            public $february = '2014-02';
            public $march = '2014-03';
            public $april = '2014-04';
            public $result;

            public function graphPrice($array, $month) {
                if ($array['date_create']->format('Y-m') == $month) {
                    $this->price[] = $array['price'];
                }
                return $this->price;
            }

            public function meanPrice($price_array) {
                $this->result = array_sum($price_array) / count($price_array);
                return $this->result;
            }

        }

        $january = new Graphical();
        $february = new Graphical();
        $march = new Graphical();
        $april = new Graphical();

        foreach ($date as $value) {
            $january->graphPrice($value, $january->january);
            $february->graphPrice($value, $february->february);
            $march->graphPrice($value, $march->march);
            $april->graphPrice($value, $april->april);
        }       
        
        ?>  
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>$</th>
                    <th>Январь</th>
                    <th>Февраль</th>
                    <th>Март</th>
                    <th>Апрель</th>
                </tr>  
            </thead>
            <tbody>
                <tr>
                    <td>
                        10000
                    </td>
                </tr>
                <tr>
                    <td>
                        5000
                    </td>
                </tr>
                <tr>
                    <td>
                        3000
                    </td>
                    <td>                        
                    </td>
                    <td>                        
                    </td>
                    <td>                        
                    </td>
                    <td>
                        <?php
                        if (empty($april->price)) {
                            
                        } else {
                            $april->meanPrice($april->price);
                            echo $april->result;
                        }
                        ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        1000
                    </td>

                    <td>
                        <?php
                        if (empty($january->price)) {
                            
                        } else {
                            $january->meanPrice($january->price);
                            echo $january->result;
                        }
                        ?>
                    </td>
                    <td>
                        <?php
                        if (empty($february->price)) {
                            
                        } else {
                            $february->meanPrice($february->price);
                            echo $february->result;
                        }
                        ?>
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td>
                        0
                    </td>
                    <td>

                    </td>
                    <td>

                    </td>

                    <td>
                        <?php
                        if (empty($march->price)) {
                            echo '0';
                        } else {
                            $march->meanPrice($march->price);
                            echo $march->result;
                        }
                        ?>
                    </td>
                </tr>
                <tr>

                </tr>
            </tbody>
        </table>
    </div>
</div>

