<div class="container">
    <div class="row">
        <div class="col-md-3">
            <form id="addVacancy" action="#" method="POST">

                <select name="companyy" select class="form-control">
                    <option value="0">Я компания</option>
                    <?php foreach ($company as $value): ?>
                        <option value="<?php echo $value->getId() ?>"><?php echo $value->getName() ?></option>
                    <?php endforeach; ?>
                </select> 

                <select name="technology" select class="form-control">
                    <option value="0">Выберите технологию:</option>
                    <?php foreach ($technology as $value): ?>
                        <option value="<?php echo $value->getId() ?>"><?php echo $value->getName() ?></option>
                    <?php endforeach; ?>
                </select>        


                <select name="position" select class="form-control">
                    <option value="0">Выберите должность:</option>
                    <?php foreach ($position as $value): ?>
                        <option value="<?php echo $value->getId() ?>"><?php echo $value->getName() ?></option>
                    <?php endforeach; ?>
                </select>            


                <select name="city" select class="form-control">
                    <option value="0">Выберите город:</option>
                    <?php foreach ($city as $value): ?>
                        <option value="<?php echo $value->getId() ?>"><?php echo $value->getName() ?></option>
                    <?php endforeach; ?>
                </select>


                <input type="text" name="vacancyName" placeholder="Название вакансии"/>
                <textarea name="vacancyDescr" rows="10" cols="70" placeholder="Описание"></textarea>
                <input type="text" name="vacancyPrice" placeholder="Зарплата, от"/>
                <input type="text" name="vacancyExpr" placeholder="Опыт, лет"/>
                <select title="Актуальность вакансии" name="vacancyActive">
                    <option value='10'>10 дней</option>
                    <option value='15'>15 дней</option>
                    <option value='20'>20 дней</option>
                    <option value='30'>30 дней</option>                    
                </select>
                <input type="submit" class="btn btn-success" value="Добавить"/>
            </form>    
        </div>
    </div>
</div>