
<script type="text/javascript">
    $(function() {
        $('.like').click(function() {
            id = $(this).attr("data-id");
            like = $(this).attr("data-like");
            likeDislike(id, like);
        });
    });
    function likeDislike(id, like) {
        var data = 'id=' + id + '&like=' + like;
        $.ajax({
            type: 'POST',
            url: '#',
            data: data,
            success: function(res) {
                $('body').html(res);
            }

        });
    }
    function comentForm(id) {
        $('#parent_id').attr('value', id);
        $('#' + id + '').append($('.well-lg'));
        $('#addForm').animate({height: "show"}, 1000);
    }
    $(function() {
        $('#addComment').click(function(e) {
            e.preventDefault();
            form = $('#addComm').serialize();
            alert(form);
            addComm(form);
        });
    });
    function addComm(form) {
        $.ajax({
            type: 'POST',
            url: '#',
            data: form,
            success: function(res) {
                $('body').html(res);
            }
        });

    }

</script>

<?php

function comToCom($arrayCommentsToComments, $valuePrimary) {
    foreach ($arrayCommentsToComments as $value) {
        if ($value->getParent()->getId() == $valuePrimary->getChild()->getId()) :
            ?>                            
            <ul class="child commentBlock" >
                <li>

                <div class="commHeader">
                    <div class="row">
                        <div class="col-md-2">
                            <div class="avatarChild">
                                <img style="width: 40px; height: 40px;" data-src=""/>
                            </div> 
                        </div>
                        <div class="col-md-3">   
                            <?= $value->getChild()->getTime()->format('Y-m-d H:m') ?>
                        </div>
                        
                        <div class="col-md-3">   
                            <span class="likeCount"><?= $value->getChild()->getLike() ?></span>
                            <button data-id="<?= $value->getChild()->getId() ?>" data-like="1" class="like btn btn-xs btn-success">+</button>
                            <button data-id="<?= $value->getChild()->getId() ?>" data-like="-1" class="like btn btn-xs btn-danger">-</button>
                            <span class="dislikeCount"> <?= $value->getChild()->getDisLike() ?></span>
                        </div>
                    </div>
                </div>
                <div >
                    <div class="text">
                        <?= $value->getChild()->getText() ?>
                    </div>    
                    <button onclick="comentForm('<?= $value->getChild()->getId() ?>')" class="btn btn-link">Ответить</button>
                    <div id="<?= $value->getChild()->getId() ?>" class="form"></div>
                    <?= comToCom($arrayCommentsToComments, $value) ?>
                </div>
                    </li>
            </ul>                          
        <?php
        endif;
    }
}
?>   
<ul id="commentsList" >
    <button onclick="comentForm('0')" class="btn btn-link">Оставить комментарий</button>
    <div id="addForm" class="well-lg" style="display:none" >
        <form id="addComm" name="newComment" method="POST" action="#" >
            <input type="text" class="form-control" name="autId" placeholder="Author id"/>                                      
            <textarea class="form-control" rows="3" placeholder="Ведите текст" name="textNewComment"></textarea>
            <input type="hidden" name="parent_id" id="parent_id" value="0"/>
            <input id="addComment" type="submit" class="btn btn-success"/> 
        </form>
    </div>   
<?php foreach ($commentsParent as $commentsParentResult) : ?>
  
    <li class="parent commentBlock" >
            <div class="avatar">
                <img style="width: 40px; height: 40px;" data-src=""/>
            </div>  
            <div class="commHeader" >
                <div class="row">
                    <div class="col-md-3">
    <?= $commentsParentResult->getComments()->getTime()->format('Y-m-d H-m') ?>
                    </div>
                    
                    <div class="col-md-2">
                        <span class="likeCount"><?= $commentsParentResult->getComments()->getLike() ?></span>
                        <button data-like="1" data-id="<?= $commentsParentResult->getComments()->getId() ?>" class="like btn btn-xs btn-success">+</button>
                        <button data-id="<?= $commentsParentResult->getComments()->getId() ?>" data-like="-1" class="like btn btn-xs btn-danger">-</button>
                        <span class="dislikeCount"> <?= $commentsParentResult->getComments()->getDisLike() ?></span>
                    </div>
                </div>
            </div>
            <div>
                <div class="text">
    <?= $commentsParentResult->getComments()->getText() ?>
                </div> 
                <button onclick="comentForm('<?= $commentsParentResult->getComments()->getId() ?>')" class="btn btn-link">Ответить</button>
                <div id="<?= $commentsParentResult->getComments()->getId() ?>" class="form"></div>
                <?php foreach ($commentsToComments as $value) : ?>
        <?php if ($value->getParent()->getId() === $commentsParentResult->getComments()->getId()) : ?>
                        <ul class="children">
                            <li class="child commentBlock" >
                                         
                                <div class="commHeader">
                                    <div class="row">
                                                                <div class="col-md-2">
                            <div class="avatarChild">
                                <img style="width: 40px; height: 40px;" data-src=""/>
                            </div> 
                        </div>
                                        <div class="col-md-3">
            <?= $value->getChild()->getTime()->format('Y-m-d H-m') ?>
                                        </div>
                                        
                                        <div class="col-md-3">
                                            <span class="likeCount"><?= $value->getChild()->getLike() ?> </span>
                                            <button data-id="<?= $value->getChild()->getId() ?>" data-like="1" class="like btn btn-xs btn-success">+</button>
                                            <button data-id="<?= $value->getChild()->getId() ?>" data-like="-1" class="like btn btn-xs btn-danger">-</button>
                                            <span class="dislikeCount"><?= $value->getChild()->getDisLike() ?></span>                                            
                                        </div>
                                    </div>
                                </div>
                                <div >
                                    <div class="text">

            <?= $value->getChild()->getText() ?>

                                    </div>
                                    <button onclick="comentForm('<?= $value->getChild()->getId() ?>')" class="btn btn-link">Ответить</button>
                                    <div id="<?= $value->getChild()->getId() ?>" class="form"></div>
            <?= comToCom($commentsToComments, $value) ?>
                                </div>
                            </li>
                        </ul>
                    <?php endif; ?>
    <?php endforeach; ?>
            </div>
        </li>
<?php endforeach; ?>
</ul>
