<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <link href="/../css/bootstrap.min.css" rel="stylesheet">
        <link href="/../css/style.css" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    </head>
    <body>
        <div class="navbar-wrapper">
            <div class="container">
                <div class="navbar navbar-inverse navbar-static-top">
                    <div class="container">
                        <div class="navbar-header">
                            </span>
                            <a href="/index" class="navbar-brand"><span class="glyphicon-class">Home</span></a>
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li><a href="/news">News</a></li>
                                <li><a href="/salary">Vacancy</a></li>
                                <li><a href="/company">Company</a></li>
                                
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        
            <?php echo $this->content; ?>
        
    <script src="/../js/bootstrap.min.js"></script>
    </body>
</html>
