<script>
  function country()  
</script>    
<div class="row">    
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            Новости из мира.... <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <?php foreach ($technology as $techValue):?>
            <li><a href="/news/tech/<?=$techValue->getId()?>"><?=$techValue->getName()?></a></li>
            <?php endforeach;?>
        </ul>
    </div>
    
</div>    

<div class="row">        
        <div class="listNews">
            <?php
            if (empty($news)) :?>
                <div class="alert alert-info">Нет результатов</div>
            <?php else :?>

               <?php foreach ($news as $newsResult) :?>
                    <div id="newsBlock" class="col-md-12">
                        <span class="label label-info"><span class="glyphicon glyphicon glyphicon-envelope"> <?= $newsResult->getComments() ?></span></span>
                     <span class="label label-default"><?= $newsResult->getTime()->format('Y-m-d') ?></span>   
                                       <a href="/news/<?= $newsResult->getTime()->format('Y') ?>/<?= $newsResult->getTime()->format('m') ?>/<?= $newsResult->getTime()->format('d') ?>/<?= $newsResult->getId() ?>">
                        <div class="thumbnail">
                            <div class="row">
                                <div class="col-md-5">
                                    <img style="width: 300px; height: 200px;" data-src="<?= $newsResult->getImg() ?>"/>
                                </div> 
                                <div class="col-md-7">
                            <h3><?= $newsResult->getName() ?></h3>
                            <div class="caption"><?= $newsResult->getShortText() ?></div>
                            </div>
                                </div>
                    </a>
                    
                    </div>
                    </div>
                <?php endforeach;?>            
            <?php endif;?>
        </div>
       
    </div>